services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Tests/'
            - '../src/*/Entity'

    redis.default:
        class: App\Infrastructure\Redis\RedisClient
        calls:
            - method: connect
              arguments:
                - 'redis'
                - 6379
                - 0

    redis.word_repository:
        class: App\Infrastructure\Redis\RedisClient
        calls:
            - method: connect
              arguments:
                - 'redis'
                - 6379
                - 1

    App\Infrastructure\Repository\Redis\Session\RedisSessionRepository:
        arguments:
            $redis: '@redis.default'

    App\Infrastructure\Repository\Redis\Game\RedisWordRepository:
        arguments:
            $redis: '@redis.word_repository'
            $dbIndex: 1

    App\Domain\Session\Service\TimerService:
        tags:
            - { name: 'app.service' }

    App\Domain\:
        resource: '../src/Domain/*/Handler/*'
        tags: ['app.message_handler']

    App\Core\Dispatcher\WebSocketDispatcher:
        arguments: []
        calls:
            - method: setHandlers
              arguments:
                - !tagged_iterator app.message_handler

    App\Infrastructure\Connection\ConnectionStorageInterface: '@App\Infrastructure\Connection\ConnectionStorage'

    App\Domain\Repository\Session\SessionRepositoryInterface: '@App\Infrastructure\Repository\Redis\Session\RedisSessionRepository'

    App\Domain\Repository\Game\RedisWordRepositoryInterface: '@App\Infrastructure\Repository\Redis\Game\RedisWordRepository'

    App\Domain\Session\Service\SessionServiceInterface: '@App\Domain\Session\Service\SessionService'

    App\GameServer:
        arguments:
            $dispatcher: '@App\Core\Dispatcher\WebSocketDispatcher'
            $connectionStorage: '@App\Infrastructure\Connection\ConnectionStorage'