services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Tests/'

    App\Application\Session\Service\TimerService:
        tags:
            - { name: 'app.service' }

    App\Util\Redis\RedisClient:
        calls:
            - method: connect
              arguments:
                - 'redis'
                - 6379

    App\Application\:
        resource: '../src/Application/*/Handler/*'
        tags: ['app.message_handler']

    App\Core\Dispatcher\MessageDispatcher:
        arguments: []
        calls:
            - method: setHandlers
              arguments:
                - !tagged_iterator app.message_handler

    App\Util\Connection\ConnectionStorage: ~

    App\Infrastructure\Repository\GameSession\GameSessionRepositoryInterface: '@App\Infrastructure\Repository\GameSession\RedisGameSessionRepository'

    App\Application\Session\Service\SessionServiceInterface: '@App\Application\Session\Service\SessionService'

    App\GameServer:
        arguments:
            $dispatcher: '@App\Core\Dispatcher\MessageDispatcher'
            $connectionStorage: '@App\Util\Connection\ConnectionStorage'
