services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Tests/'
            - '../src/*/Entity'

    App\Domain\Session\Service\TimerService:
        tags:
            - { name: 'app.service' }

    App\Infrastructure\Redis\RedisClient:
        calls:
            - method: connect
              arguments:
                - 'redis'
                - 6379

    App\Domain\:
        resource: '../src/Domain/*/Handler/*'
        tags: ['app.message_handler']

    App\Core\Dispatcher\MessageDispatcher:
        arguments: []
        calls:
            - method: setHandlers
              arguments:
                - !tagged_iterator app.message_handler

    App\Infrastructure\Connection\ConnectionStorageInterface: '@App\Infrastructure\Connection\ConnectionStorage'

    App\Domain\Repository\Session\SessionRepositoryInterface: '@App\Infrastructure\Repository\Redis\Session\RedisSessionRepository'

    App\Domain\Repository\Game\RedisWordRepositoryInterface: '@App\Infrastructure\Repository\Redis\Game\RedisWordRepository'

    App\Domain\Session\Service\SessionServiceInterface: '@App\Domain\Session\Service\SessionService'

    App\GameServer:
        arguments:
            $dispatcher: '@App\Core\Dispatcher\MessageDispatcher'
            $connectionStorage: '@App\Infrastructure\Connection\ConnectionStorage'
